### ISSUE TITLE
Mistaken channel axis?

### ISSUE THREAD

**Issue by jmzhao** [broadinstitute/keras-resnet#15]
Should `a_shape[3] == b_shape[3]` at [block.py#L110](https://github.com/broadinstitute/keras-resnet/blob/master/keras_resnet/block.py#L110) be `a_shape[1] == b_shape[1]`?

**Comment by 0x00b1** [comment]
Yep!

**Comment by 0x00b1** [comment]
@jmzhao Feel free to send a PR! If you don't have time, I'll fix this week.

**Comment by 0x00b1** [comment]
Fixed. :)
