### ISSUE TITLE
1D ResNet?

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/keras-resnet#49]
I've been trying to use this resnet on a 1D feature tensor..DNA-sequence! but I get errors using the default ResNet object since I do not have enough dimensions. I tried writing my own ResNet1D using the framework that you have going here, but have failed, thus far. 

A few pointers would be appreciated!

**Comment by yfarjoun** [comment]
figured it out. if there's interest I can submit a PR

**Comment by vincenzodentamaro** [comment]
I am interested, please let me know.
